import 'dotenv/config';

const {
    SCHOOLINKA_NODE_ENV,
    SCHOOLINKA_PORT,
    SCHOOLINKA_PROD_DATABASE_URL,
    SCHOOLINKA_PROD_BCRYPT_SALT_ROUNDS,
    SCHOOLINKA_PROD_JWT_SECRET_KEY,
} = process.env

export default {
    SCHOOLINKA_NODE_ENV,
    SCHOOLINKA_PORT,
    SCHOOLINKA_URL: SCHOOLINKA_PROD_DATABASE_URL,
    SCHOOLINKA_BCRYPT_SALT_ROUNDS: SCHOOLINKA_PROD_BCRYPT_SALT_ROUNDS,
    SCHOOLINKA_JWT_SECRET_KEY: SCHOOLINKA_PROD_JWT_SECRET_KEY,
}